### ISSUE TITLE
Song names appear as "play" in the playlist when using Soundcloud

### ISSUE THREAD

**Issue by FortuneNT** [ProGEEK/kodi-resume#1]
First of all I want to say the add-on works great and is exactly where I was looking for.
But unfortunately the add-on doesn't restore the song names in the playlist when using Soundcloud. All Soundcloud songs are shown as "play" in the playlist, but are shown correctly by the music player.
Is there a way to fix this?

Thanks in advance
![kodi](https://cloud.githubusercontent.com/assets/9203067/10870327/3c0e4702-80c8-11e5-8f96-1085547907ed.png)

**Comment by ProGEEK** [comment]
This is not my code, I take no credit for any of it other than the modifications I have made.

This repository is not being maintained nor developed.

Sorry, You're on your own.
