### ISSUE TITLE
Feature Request: Play Second to Last Video

### ISSUE THREAD

**Issue by justinro** [ProGEEK/kodi-resume#2]
I'd like to modify this plugin to include an option of restoring the Second to last Video's state. 

This would (hopefully) allow a user to mimic the "Previous" button on a remote where they could swap back and forth between two videos with a hotkey press. 

I've already modified the plugin to work with a hotkey press instead of on launch, but can't figure out how you're storing the video and if it could retrieve the second to last video played.
Thanks!

**Comment by ProGEEK** [comment]
This is not my code, I take no credit for any of it other than the modifications I have made.

This repository is not being maintained nor developed.

Sorry, You're on your own.
